"""Render every Chartroom icon asset from assets/icon/chartroom.svg.

Requires rsvg-convert (librsvg) and Pillow; the macOS .icns also needs iconutil (macOS only).

    python3 scripts/make_icons.py

Outputs:
    assets/icon/Chartroom.icns   macOS bundle icon (full canvas, with the macOS margin)
    assets/icon/chartroom.ico    Windows executable icon (tile only)
    assets/icon/chartroom.png    1024 px tile, for documentation and Linux desktop files
    src/app_icon.hpp             64 px RGBA window icon for GLFW (Windows and Linux title bars)
    web/shell.html               favicon data URI, between the chartroom-icon markers
"""
import base64
import io
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
ICON = ROOT / 'assets' / 'icon'
SVG = ICON / 'chartroom.svg'


def render(svg_text, size):
    with tempfile.TemporaryDirectory() as tmp:
        src, out = pathlib.Path(tmp) / 'icon.svg', pathlib.Path(tmp) / 'icon.png'
        src.write_text(svg_text)
        subprocess.run(['rsvg-convert', '-w', str(size), '-h', str(size), str(src), '-o', str(out)], check=True)
        return Image.open(out).convert('RGBA')


def main():
    full = SVG.read_text()
    # Outside macOS, icons are expected to fill their square: crop the canvas to the tile.
    tile = full.replace('viewBox="0 0 1024 1024"', 'viewBox="100 100 824 824"', 1)
    if tile == full:
        sys.exit('chartroom.svg must keep viewBox="0 0 1024 1024"')

    render(tile, 1024).save(ICON / 'chartroom.png')

    sizes = [16, 24, 32, 48, 64, 128, 256]
    images = [render(tile, s) for s in sizes]
    images[-1].save(ICON / 'chartroom.ico', sizes=[(s, s) for s in sizes], append_images=images[:-1])

    if shutil.which('iconutil'):
        with tempfile.TemporaryDirectory() as tmp:
            iconset = pathlib.Path(tmp) / 'Chartroom.iconset'
            iconset.mkdir()
            for s in (16, 32, 128, 256, 512):
                render(full, s).save(iconset / f'icon_{s}x{s}.png')
                render(full, s * 2).save(iconset / f'icon_{s}x{s}@2x.png')
            subprocess.run(['iconutil', '-c', 'icns', str(iconset), '-o', str(ICON / 'Chartroom.icns')], check=True)
    else:
        print('iconutil not found: kept the existing Chartroom.icns')

    window = render(tile, 64)
    data = window.tobytes()
    rows = [', '.join(str(b) for b in data[i:i + 24]) for i in range(0, len(data), 24)]
    (ROOT / 'src' / 'app_icon.hpp').write_text(
        '#pragma once\n'
        '// Generated by scripts/make_icons.py from assets/icon/chartroom.svg. Do not edit.\n'
        'namespace cr::app_icon {\n'
        'inline constexpr int size = 64;\n'
        'inline constexpr unsigned char rgba[] = {\n    ' + ',\n    '.join(rows) + '};\n'
        '} // namespace cr::app_icon\n')

    png = io.BytesIO()
    render(tile, 64).save(png, 'PNG', optimize=True)
    link = ('<!-- chartroom-icon --><link rel="icon" type="image/png" href="data:image/png;base64,'
            + base64.b64encode(png.getvalue()).decode() + '"><!-- /chartroom-icon -->')
    shell = ROOT / 'web' / 'shell.html'
    html = shell.read_text()
    if '<!-- chartroom-icon -->' in html:
        html = re.sub(r'<!-- chartroom-icon -->.*?<!-- /chartroom-icon -->', lambda _: link, html, flags=re.S)
    else:
        html = html.replace('</title>', '</title>' + link, 1)
    shell.write_text(html)
    print('Icons written to', ICON.relative_to(ROOT), 'src/app_icon.hpp and web/shell.html')


if __name__ == '__main__':
    main()
